// Appointment Status Constants
export const APPOINTMENT_STATUS = {
  SCHEDULED: "scheduled",
  CONFIRMED: "confirmed",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
};

export const APPOINTMENT_STATUS_LABELS = {
  [APPOINTMENT_STATUS.SCHEDULED]: "Scheduled",
  [APPOINTMENT_STATUS.CONFIRMED]: "Confirmed",
  [APPOINTMENT_STATUS.COMPLETED]: "Completed",
  [APPOINTMENT_STATUS.CANCELLED]: "Cancelled",
};

export const APPOINTMENT_STATUS_OPTIONS = [
  {
    value: APPOINTMENT_STATUS.SCHEDULED,
    label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.SCHEDULED],
  },
  {
    value: APPOINTMENT_STATUS.CONFIRMED,
    label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.CONFIRMED],
  },
  {
    value: APPOINTMENT_STATUS.COMPLETED,
    label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.COMPLETED],
  },
  {
    value: APPOINTMENT_STATUS.CANCELLED,
    label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.CANCELLED],
  },
];
